// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://culogzxomnalpnctrcfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1bG9nenhvbW5hbHBuY3RyY2Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MTIwNjgsImV4cCI6MjA1NTk4ODA2OH0.8HPXtmabBek87kbRoWCLSxoEta-kp91CTOGfbGOW4p0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);